### ISSUE TITLE
SuperAPI code practice issues

### ISSUE THREAD

**Issue by PEMapModder** [PMPlugins/Development#10]
Using static object class properties is discouraged in plugins.

**Comment by legoboy0215** [comment]
Oops… Sorry. Then how will people get the instance?
$this->getPluginMrg()->getPlugin("SuperAPI") or similar?

**Comment by PEMapModder** [comment]
Yes. `$server->getPluginManager()->getPlugin("SuperAPI");`

**Comment by legoboy0215** [comment]
Thanks!

**Comment by PEMapModder** [comment]
Or you can create a function like this:

``` php
public static function getInstance($server = null){
  $server = ($server === null) ? Server::getInstance() : $server;
  $ret = $server->getPluginManager()->getPlugin("SuperAPI");
  if(!($ret instanceof SAPI) or !$ret->isEnabled()) throw new \RuntimeException("SuperAPI not loaded");
  return $ret;
}
```

**Comment by legoboy0215** [comment]
OMG so complicated... But this is cool.. I only don't understand throw.

**Comment by jojoe77777** [comment]
Throwing an error... It just makes the error happen. Tells the error to trigger.

**Comment by legoboy0215** [comment]
Thanks! Umm...
If $server equals null is true then make $server Server::getInstance() then if false then just be null.
$ret is getting the plugin instance and if the plugin instance is not a instance of SAPI then throw a new error (Which is most likely to be that the plugin is NOT loaded.) If everything is successful then return the SAPI instance. Can I use this piece of code now?

**Comment by legoboy0215** [comment]
I want to ask a VERY off topic thing.. How did you get into MCPE coding?

**Comment by jojoe77777** [comment]
Btw, Legoboy, check RLamp forums private messages

**Comment by jojoe77777** [comment]
Me or PEMM?

**Comment by legoboy0215** [comment]
PEM

**Comment by jojoe77777** [comment]
k

**Comment by PEMapModder** [comment]
I don't think it is complicated. You read it correctly :P

**Comment by PEMapModder** [comment]
@legoboy0215 it has nothing to do with "MCPE coding". It is general coding. What do you mean?

**Comment by legoboy0215** [comment]
I mean MCPE gaming.

**Comment by PEMapModder** [comment]
I updated the snippet a bit to check enabled.

**Comment by legoboy0215** [comment]
Thanks!
