### ISSUE TITLE
Suggestions for SuperAPI?

### ISSUE THREAD

**Issue by legoboy0215** [PMPlugins/Development#11]
Any suggestions?

**Comment by jojoe77777** [comment]
Invisibility API?

**Comment by jojoe77777** [comment]
...If needed, I heard about $player->hidePlayer($player2); in the PM API  (not quite sure how to use it)

**Comment by legoboy0215** [comment]
Um...
#ReadtheDocs :)

**Comment by jojoe77777** [comment]
Lol I generated docs and uploaded them but didn't read them XD But Slapper doesn't use $whatever->hidePlayer, so I didn't need to know it.

**Comment by legoboy0215** [comment]
Oh.
