### ISSUE TITLE
TellRaw - @a not working correctly

### ISSUE THREAD

**Issue by jojoe77777** [PMPlugins/Development#13]
I tried "/tellraw @a Hello"... but it only sent the message to me, when I had another account logged in too. I tried different names, but still the same.

**Comment by jojoe77777** [comment]
Fixed, and changed to *.

**Comment by legoboy0215** [comment]
Is it fixed? Changed what?

**Comment by jojoe77777** [comment]
The message, for some reason, was only going to the player who logged in first, but I fixed that, and changed it to "*"

**Comment by legoboy0215** [comment]
:+1:
