### ISSUE TITLE
Add even more mobs to Slapper

### ISSUE THREAD

**Issue by jojoe77777** [PMPlugins/Development#14]
We still need the mobs from 0.11, plus the new ones coming in 0.12 (Iron Golem, Snow Golem, Ocelot, etc)

**Comment by legoboy0215** [comment]
Really? Golems?

**Comment by jojoe77777** [comment]
Yeah, and Ghasts, blazes, etc.

**Comment by legoboy0215** [comment]
ooo

**Comment by jojoe77777** [comment]
It's coming out in a few days!

**Comment by legoboy0215** [comment]
:+1:

**Comment by jojoe77777** [comment]
All mobs from 0.11 added, time to wait for 0.12.

**Comment by legoboy0215** [comment]
:)

**Comment by jojoe77777** [comment]
Expect the 0.12 mobs (snowman, iron golem, ocelot, zombie villager, blaze, ghast) to be added by tomorrow!

**Comment by legoboy0215** [comment]
I know. IT IS OUT!!!!

**Comment by jojoe77777** [comment]
Uhh yeah. Lol.

**Comment by legoboy0215** [comment]
Ooooppppsss... :P

**Comment by legoboy0215** [comment]
BTW, I think there will be no network channels in PM 1.6. Check the source code.

**Comment by jojoe77777** [comment]
Well Slapper still works with the network channels.

**Comment by jojoe77777** [comment]
I tested it today.

**Comment by legoboy0215** [comment]
Really? oooo

**Comment by jojoe77777** [comment]
_coding right now_

**Comment by jojoe77777** [comment]
I don't know most of the network IDs for the new mobs...

**Comment by jojoe77777** [comment]
Found network IDs on Minecraft Wiki :D

**Comment by legoboy0215** [comment]
lol

**Comment by legoboy0215** [comment]
Neat link: http://goo.gl/sDoYQ5

**Comment by jojoe77777** [comment]
uhh wat it says the page doesn't exist

**Comment by legoboy0215** [comment]
Oh. Uhh... Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/600.8.9 (KHTML, like Gecko) Version/8.0.8 Safari/600.8.9

**Comment by legoboy0215** [comment]
You really have a Mac! This proves that I trust you.

**Comment by jojoe77777** [comment]
Uhh what? Did that website get the data?

**Comment by legoboy0215** [comment]
No. Github API. That website was a troll :P

**Comment by jojoe77777** [comment]
ooh, how do you use the GitHub API to get that?

**Comment by jojoe77777** [comment]
Also, I have coded the new mobs.

**Comment by jojoe77777** [comment]
But if you run the plugin on a 1.5 server and try to spawn the new mobs, clients will crash until the plugin is removed...

**Comment by legoboy0215** [comment]
Of course............................................................................................................................................ I will not update to PM 1.6 until it becomes stable.

**Comment by legoboy0215** [comment]
... just need to know the golem's entity id.

**Comment by jojoe77777** [comment]
Iron g: 20, snow g: 21

**Comment by legoboy0215** [comment]
Thanks!

**Comment by jojoe77777** [comment]
Added more mobs in 1.2.7.
