### ISSUE TITLE
All mobs turn into Slapper mobs

### ISSUE THREAD

**Issue by jojoe77777** [PMPlugins/Development#16]
For some reason, whenever I use a spawn egg, it spawns a slapper mob.

**Comment by jojoe77777** [comment]
Also, when I have Slapper installed, I can use any spawn egg.... And it makes a slapper mob of that type.

**Comment by legoboy0215** [comment]
Really?

**Comment by jojoe77777** [comment]
Yeah... I added a var_dump into entityDamageEvent and it showed that they were slapper mobs.

**Comment by TahaTheHacker** [comment]
I have that creepy bug too...

**Comment by legoboy0215** [comment]
... #BlameJojoe77777 or #BlameLegoboy0215

**Comment by TahaTheHacker** [comment]
I won't blame if i didn't even *Help*

**Comment by legoboy0215** [comment]
:P I did not help too.

**Comment by jojoe77777** [comment]
It seems to be fixed if the server is restarted....

**Comment by TahaTheHacker** [comment]
No.

**Comment by Jorti1** [comment]
I have the same bug , but I don't mind because u can use /slapper remove on it
