### ISSUE TITLE
Can Add command on Slapper

### ISSUE THREAD

**Issue by EnderKenji** [PMPlugins/Development#19]
For Slapper 1.2.7

I wanna add command on slapper.. but its dont work.
I use /slapper edit <id> addc <command> this format, but it said 'An Unknown error to present this ...' 

I also tested using config,, also can't 

Teach me how or fix it please?

**Comment by legoboy0215** [comment]
Post the error on console here.

**Comment by EnderKenji** [comment]
10.11 01:34:58 [Server] Server thread/CRITICAL Unhandled exception executing command 'slapper edit 8 addc /help' in slapper: Class slapper\entities\pocketmine\nbt\tag\String not found

**Comment by EnderKenji** [comment]
thread/CRITICAL ClassNotFoundException: "Class slapper\entities\pocketmine\nbt\tag\String not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144
10.11 01:33:54 [Server] Server thread/CRITICAL Unhandled exception executing command 'slapper edit 8 addc sm hey' in slapper: Class slapper\entities\pocketmine\nbt\tag\String not found

**Comment by jojoe77777** [comment]
Try this version: https://www.dropbox.com/s/obabja4vmw2to2c/Slapper_v1.2.7.phar?dl=0

**Comment by legoboy0215** [comment]
Oh lol...

**Comment by EnderKenji** [comment]
But how to add command? Need inculde '/' or not?
I added and when I hit slapper, the command did not work...

I do /slapper edit 1 addc help & /slapper edit 1 addc /help

And it said command added.

I restarted server, i try to hit , and nothing happen...

**Comment by jojoe77777** [comment]
Don't include '/'.

**Comment by EnderKenji** [comment]
I did, same.

**Comment by jojoe77777** [comment]
Please tell us what '/slapper edit <id> listcommands' says.

**Comment by EnderKenji** [comment]
[S] help

**Comment by EnderKenji** [comment]
But when I hit the slapper it doesnt works :/

**Comment by legoboy0215** [comment]
Do you have a world protect plugin?

**Comment by EnderKenji** [comment]
Yee

**Comment by legoboy0215** [comment]
@jojoe77777 , isCancelled() would result if you use a PVP or damage protect plugin, you won't be able to tap it :P

**Comment by EnderKenji** [comment]
Ohhh Ok, So how if i want to let slapper works and no pvp ._.

**Comment by jojoe77777** [comment]
@legoboy0215 I'm pretty sure I removed that...

**Comment by legoboy0215** [comment]
Yep. Sorry!

**Comment by EnderKenji** [comment]
Then how? QAQ

**Comment by jojoe77777** [comment]
Does anything happen in the console when you hit the entity?

**Comment by EnderKenji** [comment]
nothing happen.... just like a normal slapper with no and command... :/

**Comment by Pub4Game** [comment]
@jojoe77777 I wanted to make a team /donate, but all of the text or given to only output to the console(

**Comment by ZeroDevOfficial** [comment]
The plugin is not on dropbox
