### ISSUE TITLE
ew cringe

### ISSUE THREAD

**Issue by jojoe77777** [PMPlugins/Development#21]
I was running my test server, "var_dump"ing packets. I disconnected, so the var_dumps stopped. A few seconds later I got this in my console:

`[06:29:39] [Server thread/CRITICAL]: Could not tick level "Worldy": Argument 1 passed to pocketmine\inventory\PlayerInventory::__construct() must be an instance of pocketmine\entity\Human, instance of slapper\entities\SlapperHuman given, called in phar:///*REMOVED*/PocketMine/PocketMine-MP.phar/src/pocketmine/entity/Human.php on line 103 and defined`

Then the server stopped responding; it crashed without closing the console.

**Comment by jojoe77777** [comment]
I think this is **possible** to fix... But I don't know if *I* can do it.

**Comment by PocketKiller** [comment]
remove the SlapperHuman class and use the Human class by pocketmine instead.

**Comment by jojoe77777** [comment]
@PocketKiller That's what I used to do, but it caused problems, and isn't friendly with other plugins.

**Comment by Vaults1** [comment]
I wish I could help, but I can't :(

**Comment by jojoe77777** [comment]
Can't reproduce this anymore.
