### ISSUE TITLE
Slapper Servercrash with Genisys version

### ISSUE THREAD

**Issue by SleepSpace9** [PMPlugins/Development#26]
Hi jojoe,

it's about the following crash:
Error: Call to undefined method slapper\entities\SlapperHuman::isSurvival()

I know you fixed the crash directly in the ImagicalMine build (https://github.com/jojoe77777/ImagicalMine/commit/cc2528ba01fc5ed3b5dc993e01df0af64ec503b1), but for stability reasons I would like to use Genisys. Is there a possibility to fix it in the plugin?

Or could you convince the Genisys-Team to change their code for working with slapper?
The Issue was already reported there (https://github.com/iTXTech/Genisys/issues/59), but it has been closed because it should be addressed to you as plugin developer.

I noticed the cooperation between ImagicalMine- and Genisys-Team, so I hope you can help.

P.S.: Many thanks for the Slapper plugin, I would hardly miss it!

**Comment by jojoe77777** [comment]
The crash in ImagicalMine was a seperate issue. I have tried to make Slapper work with Genisys but it kept crashing.

**Comment by jojoe77777** [comment]
More info:
I fixed the isSurvival crash, but then I got this:

> Error: Call to a member function getWindowId() on double

And I don't know how to fix that.

**Comment by SleepSpace9** [comment]
Oh, that's a pity. :-(
I guessed there must be a difference between ImagicalMine and Genisys. The only one I found was an additional closing square bracket in **PlayerListPacket.php** at line 65, which is propably a fault:

``` php
...
        }else{
                $this->putUUID($entry[0]]);
            }
...
```

**Comment by jojoe77777** [comment]
> Oh, that's a pity. :-(
> I guessed there must be a difference between ImagicalMine and Genisys. The only one I found was an additional closing square bracket in PlayerListPacket.php at line 65, which is propably a fault:
> 
> ...
>         }else{
>                 $this->putUUID($entry[0]]);
>             }
> ...

Thanks but I already fixed that.
https://github.com/jojoe77777/ImagicalMine/commit/dc53339fa1fc783abbfa6c573fec90af086fa312

**Comment by ZeroDevOfficial** [comment]
Genisys Crash Dump Mon Jan 18 23:51:25 UTC 2016

Error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name
File: myzip:///plugins/Slapper_DEV.zip#Slapper_DEV/src/slapper/main
Line: 17
Type: E_COMPILE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
此次出错由插件引起

Code:
[8] use pocketmine\entity\Entity;
[9] use pocketmine\event\entity\EntityDamageByEntityEvent;
[10] use pocketmine\event\entity\EntityDamageEvent;
[11] use pocketmine\event\Listener;
[12] use pocketmine\Item\Item;
[13] use pocketmine\nbt\tag\Byte;
[14] use pocketmine\nbt\tag\Compound;
[15] use pocketmine\nbt\tag\Double;
[16] use pocketmine\nbt\tag\Enum;
[17] use pocketmine\nbt\tag\Float;

**Comment by SleepSpace9** [comment]
After ImagicalMine had the same crash problem with Slapper (*Error: Call to undefined method slapper\entities\SlapperHuman::isSurvival()*), they could fix it now in their server code:

https://github.com/robske110/ImagicalMine/commit/c903bd4b69f4d8b60897d6e14602dabea973f088

I already opened a new issue at Genisys, hopefully they also fix it und your can put your energy in making Slapper plugin ready for php7 (EpicSteve33 and I would appreciate it)?  :wink:

**Comment by SleepSpace9** [comment]
I close this issue because the latest version works for me.
