### ISSUE TITLE
i cannot use rca {player} kit ironkit

### ISSUE THREAD

**Issue by dries-c** [PMPlugins/Development#27]
IronKit $4000:
- effect {player} clear
- rca {player} kit iron kit

problem
[16:32:30] [INFO]: Took all effects from driesboy
[16:32:30] [INFO]: Player not found.

**Comment by ZeroDevOfficial** [comment]
Is there a space in the command?

**Comment by dries-c** [comment]
no

**Comment by Driesboy** [comment]
haha now you can use 
IronKit $4000:

effect {name} clear
rca {name} kit iron kit

**Comment by jojoe77777** [comment]
The command is working, it just says "Player not found." anyway. Fixed in 1.2.9.
