### ISSUE TITLE
Slapper deleted?

### ISSUE THREAD

**Issue by Jorti1** [PMPlugins/Development#28]
Each time my server goes offline or restart , all my slappers are deleted . I don't know why , I allow PocketMine-MP to get 650mb of ram???? Do u need more info?

**Comment by jojoe77777** [comment]
Sorry, not sure why this is happening. try saving before restarting.

**Comment by Jorti1** [comment]
I do /save-all

Not sure but maybe it could be because worlds aren't loaded on time,  if u want to see for ur self u are able to ask for the IP,  [0.14.0]

**Comment by Shock95** [comment]
This is happening to me too...
