### ISSUE TITLE
cringe

### ISSUE THREAD

**Issue by jojoe77777** [PMPlugins/Development#3]
cringe

**Comment by legoboy0215** [comment]
Ok. I will check out.

**Comment by jojoe77777** [comment]
I'm gonna see what happens if keep trying random numbers and types into "Rotation" for the NBT...

**Comment by jojoe77777** [comment]
:O it worked! This issue should be fixed soon.

**Comment by jojoe77777** [comment]
O_O I went back to check it out, and found no problems. creepy.

**Comment by jojoe77777** [comment]
I was looking at the ground while I was spawning them.

**Comment by legoboy0215** [comment]
lol :)
