### ISSUE TITLE
Slapper Github page?

### ISSUE THREAD

**Issue by legoboy0215** [PMPlugins/Development#4]
Upload a github page to the slapper plugin page in PM Forums...

**Comment by jojoe77777** [comment]
Maybe when I get 1.2 out.

**Comment by legoboy0215** [comment]
IK. Just saying :+1:

**Comment by jojoe77777** [comment]
How long are you banned from PM Forums for?

**Comment by legoboy0215** [comment]
Until Sep. 14

**Comment by legoboy0215** [comment]
IK the reason. I posted a thread that was too short... :(

**Comment by jojoe77777** [comment]
I try not to post many threads so that doesn't happen to me

**Comment by legoboy0215** [comment]
lolol
