### ISSUE TITLE
Slapper - Some mobs float a bit

### ISSUE THREAD

**Issue by jojoe77777** [PMPlugins/Development#6]
Some mobs, like CaveSpiders, spawn a bit above the block and float there.

**Comment by jojoe77777** [comment]
***_Using this to chat**_\* In the latest commit, I meant "Legoboy" not Legibly... Annoying auto-correct.

**Comment by legoboy0215** [comment]
lol

**Comment by legoboy0215** [comment]
This is normal  I think. Creepers also float actually.

**Comment by jojoe77777** [comment]
Nah, I checked Singleplayer, they don't float in there.

**Comment by legoboy0215** [comment]
Cuz you are flying?

**Comment by jojoe77777** [comment]
Nah I'm not, it was just a problem with code, I've nearly fixed it.

**Comment by legoboy0215** [comment]
Ok! Best guy in the world apart from some other guys lol :)

**Comment by jojoe77777** [comment]
Lol :)

**Comment by legoboy0215** [comment]
Fixed. I wanna see the problem :)

**Comment by jojoe77777** [comment]
Oh yeah, I forgot. I already fixed it for some XD

**Comment by jojoe77777** [comment]
Fixed for all entities.. I think.
