### ISSUE TITLE
What should we do with Slapper

### ISSUE THREAD

**Issue by jojoe77777** [PMPlugins/Development#8]
Do you think we should add a file for each spawned mob?

**Comment by jojoe77777** [comment]
So you can set the Rotation, Size, Adult/Baby, what it's holding, ect.

**Comment by legoboy0215** [comment]
Yes. I think that is important. It will be easy to add an API for that.

**Comment by legoboy0215** [comment]
BTW, I learned how to use Git!!!!!

**Comment by jojoe77777** [comment]
Cool! And also, something more important to do with the files... Commands!

**Comment by legoboy0215** [comment]
Yeah. Thats easy too.

**Comment by jojoe77777** [comment]
But I don't know how to make configs for each one... 0_0

**Comment by legoboy0215** [comment]
Thats where I come in... But then we need to limit one name only.

**Comment by jojoe77777** [comment]
Or have IDs...

**Comment by jojoe77777** [comment]
Like... A mob named "Meh", file named Meh.txt(yml), if you spawn another one named Meh, the file is Meh_1.txt.... or something like that.

**Comment by legoboy0215** [comment]
IK. I will try it. First ask in forums. Use a conversation with PEMapModder... :)

**Comment by jojoe77777** [comment]
I'm scared. I don't wanna get banned XD

**Comment by legoboy0215** [comment]
Is that a joke xD

**Comment by jojoe77777** [comment]
Kinda XD

**Comment by legoboy0215** [comment]
lol

**Comment by jojoe77777** [comment]
I'll have a look in SimpleAuth code so I'll try to make files.

**Comment by legoboy0215** [comment]
Ok. I checked

**Comment by jojoe77777** [comment]
But I'm not sure what to do with the file names... Maybe something like "NameHere.sheep.yml" for a Sheep with the name NameHere?

**Comment by legoboy0215** [comment]
Yea. I think make folders. slappers/sheep/lol.yml

**Comment by jojoe77777** [comment]
But the mobs aren't "slappers". They are entities.

**Comment by legoboy0215** [comment]
Just a suggestion :)

**Comment by jojoe77777** [comment]
Actually... I think files will only work for commands.

**Comment by jojoe77777** [comment]
So.. maybe we should just change the commands.

**Comment by jojoe77777** [comment]
Like "/slapper addcommand npcname say_lol_{player},me_is_cool"... and "/slapper addmob Pig xyz:128-64-128,dir:180-0,baby:true"

**Comment by legoboy0215** [comment]
Maybe, but first stick with the config.

**Comment by jojoe77777** [comment]
I was thinking that this command would add info into the config, so old configs wouldn't break.

**Comment by legoboy0215** [comment]
Yeah...

**Comment by jojoe77777** [comment]
Thinking about this idea again... @PEMapModder, what do you think? Use files/a file/some sort of database to store entity data? Then send packets to make the entities appear, and listen for interact packets with the Entity ID that was sent to the client to detect when it's tapped? Not sure if this will work, just thinking off the top of my head. If this worked, it would *hopefully* mean less errors/crashes and less lag, since the entities wouldn't be actually exist.
